name: Build and Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/kanbancord-api:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME \
            .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME